<%- include('partials/header'); -%>

<form>
    <h2>Reset Your Password </h2>
    <label for="password">New Password</label>
    <input type="password" name="password" required />
   
    <label for="confirm_password">Confirm Password</label>
    <input type="password" name="confirm_password" required />
    <div id="password" class="error"></div>
    <button>Save Password</button>

</form>

<%- include('partials/footer'); -%>
<% let id = token%>
<script>

    const form = document.querySelector('form');
    const password = document.querySelector('#password');
    const confPassword = document.querySelector('#conf_password');



    form.addEventListener('submit', async (e) => {
        e.preventDefault();
        //console.log('reset password page . password checking', password, password.value)
        // reset errors
        password.textContent = '';
        let id ="<%=id%>"
        console.log(id);


        if (form.password.value != form.confirm_password.value) {

            password.textContent = "password do not match";

        }

        else {
            
            const url = "http://localhost:3000/reset-password/" + id;
            console.log('url we want to direct',url);
            try {
                const res = await fetch(url, {
                    method: 'PUT',
                    body: JSON.stringify({ password: form.password.value }),
                    headers: { 'Content-Type': 'application/json' }
                });
                const data = await res.json();
                console.log(data);
                if (data.message) {

                    password.textContent = data.message;
                    setTimeout(function(){ 
                        location.assign('/login');
                     }, 5000);

                }
                if (data.errors) {

                    password.textContent = data.errors.password;
                }
                if(data.error){
                    password.textContent = data.error;
                }

            }
            catch (err) {
                console.log(err);
            }
        }
    });


</script>